server:
  port: 9527

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://cloud.eureka.server7001.com:7001/eureka,http://cloud.eureka.server7003.com:7003/eureka

spring:
  application:
    name: cloud-payment-gateway

  cloud:
    gateway:
      discovery:
        locator:
          # 开启从注册中心动态创建路由功能，利用微服务名进行路由
          enabled: true
      routes:
        - id: payment_getPayment
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/getPayment/{id},/payemnt/create
          filters:
            - AddRequestHeader=X-Request-red, blue