server:
  port: 8801
spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      # 此配置要绑定的rabbitmq的服务信息
      binders:
        # 表示定义的名称，用于binding整合
        defaultRabbit:
          # 消息组件类型
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:
        # 这个名字是一个通道的名称
        custom-out-0:
          # 表示要使用的Exchange名称定义
          destination: studyExchange
          # 消息类型
          content-type: applcation/json
          # 设置要绑定的消息服务的具体配置
          #binder: rabbit

# 服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://cloud.eureka.server7001.com:7001/eureka,http://cloud.eureka.server7003.com:7003/eureka




