server:
  port: 80

spring:
  application:
    name: cloud-order-hystrix-service
#将客户端注册到 eureka 服务列表内
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://cloud.eureka.server7001.com:7001/eureka,http://cloud.eureka.server7003.com:7003/eureka
  instance:
    instance-id: cloud-order-hystrix-service-80
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认是30秒）
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认是90s） 超时将会剔除服务实例
    lease-expiration-duration-in-seconds: 2
feign:
  circuitbreaker:
    enabled: true
