package com.mybatis.demo.mapper;

import com.mybatis.demo.entity.Salary;
import com.mybatis.demo.entity.SalaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SalaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_salary
     *
     * @mbggenerated Fri Dec 30 14:20:23 CST 2022
     */
    int countByExample(SalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_salary
     *
     * @mbggenerated Fri Dec 30 14:20:23 CST 2022
     */
    int deleteByExample(SalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_salary
     *
     * @mbggenerated Fri Dec 30 14:20:23 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_salary
     *
     * @mbggenerated Fri Dec 30 14:20:23 CST 2022
     */
    int insert(Salary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_salary
     *
     * @mbggenerated Fri Dec 30 14:20:23 CST 2022
     */
    int insertSelective(Salary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_salary
     *
     * @mbggenerated Fri Dec 30 14:20:23 CST 2022
     */
    List<Salary> selectByExample(SalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_salary
     *
     * @mbggenerated Fri Dec 30 14:20:23 CST 2022
     */
    Salary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_salary
     *
     * @mbggenerated Fri Dec 30 14:20:23 CST 2022
     */
    int updateByExampleSelective(@Param("record") Salary record, @Param("example") SalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_salary
     *
     * @mbggenerated Fri Dec 30 14:20:23 CST 2022
     */
    int updateByExample(@Param("record") Salary record, @Param("example") SalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_salary
     *
     * @mbggenerated Fri Dec 30 14:20:23 CST 2022
     */
    int updateByPrimaryKeySelective(Salary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_salary
     *
     * @mbggenerated Fri Dec 30 14:20:23 CST 2022
     */
    int updateByPrimaryKey(Salary record);
}