server:
  port: 83
spring:
  application:
    name: cloud-nacos-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

service-url:
  nacos-user-service: http://nacos-payment-provider
# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"