#配置端口
server:
  port: 80

spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://localhost:3308/test?characterEncoding=utf-8&useSSL=false
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_1:
          url: jdbc:mysql://localhost:3308/mybatis-plus?characterEncoding=utf-8&useSSL=false
          username: root
          password: 123456
          driver-class-name: com.mysql.jdbc.Driver

#MyBatis-Plus相关配置
mybatis-plus:
  #mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    #配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#设置Mybatis-Plus的全局配置
  global-config:
    db-config:
      table-prefix: mybatis_,
      id-type: assign_id

  type-aliases-package: com.honor.mybatisplus.entity



